#!/bin/bash

display_current_date_time() {
    echo "$(date)"
}

openrcfile=$1
tag=$2
ssh_key=$3
required_dev_servers=$(cat servers.conf)

def_network="${tag}_network"
def_subnet="${tag}_subnet"
def_keypair="${tag}_key"
def_router="${tag}_router"
def_security_grp="${tag}_security_group"
haproxyserv="${tag}_HAproxy"
haproxyserv2="${tag}_HAproxy2"
bastionserv="${tag}_bastion"
devlop_serv="${tag}_dev"
virtualip="${tag}_vip"
sshconf_file="config"
knownhosts="known_hosts"
hostsfile="hosts"
floating_ip2=$(cat floatipadd2)

# Function to delete servers
clean_up_servers() {
  devserv=($(openstack server list --name "$tag" -c ID -f value))
  n=${#devserv[@]}

  # Loop through each server and delete it
  if [[ -n "$devserv" ]]; then
    echo "$(date) $n servers are available so deleting servers"

    # Initialize a counter variable
    i=0

    # Loop through each server and delete it
    while [ $i -lt $n ]; do
      no_serv="${devserv[$i]}"
      openstack server delete "$no_serv"
      ((i++))
    done
