#!/bin/bash
display_current_date_time() {
    echo "$(date)"
}
openrcfile=$1
tag=$2
ssh_key=$3
no_of_serv=3   

display_current_date_time
echo "Starting deployment of $tag using $openrcfile for credentials." 
source $openrcfile  

def_network="$2_network"
def_subnet="$2_subnet"
def_keypair="$2_key"

 

             
