#!/bin/bash

display_current_date_time() {
    echo "$(date)"
}

openrcfile=$1
tag=$2
ssh_key=$3

progress=0
echo "Operation mode started run for tag: $tag using $openrcfile for credentials"
source $openrcfile


def_network="${tag}_network"
def_subnet="${tag}_subnet"
def_keypair="${tag}_key"
def_router="${tag}_router"
def_security_grp="${tag}_security_group"
haproxyserv="${tag}_HAproxy"
haproxyserv2="${tag}_HAproxy2"
bastionserv="${tag}_bastion"
devlop_serv="${tag}_dev"
virtualip="${tag}_vip"
sshconf_file="config"
knownhosts="known_hosts"
hostsfile="hosts"

removeconf(){
   if test -f "$sshconf_file"; then
    rm "$sshconf_file"
   fi

   if test -f "$hostsfile"; then
    rm "$hostsfile"
   fi

}
createconf(){
    floataddr_bastion=$(openstack server list --name "$bastionserv" -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
    floataddr_proxy1=$(openstack server show "$haproxyserv" -c addresses | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
    floataddr_proxy2=$(openstack server list --name "$haproxyserv2" -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
    echo "$(date) Generating config file"
    echo "Host $bastionserv" >>"$sshconf_file"
    echo "   User ubuntu" >>"$sshconf_file"
    echo "   HostName $floataddr_bastion" >>"$sshconf_file"
    echo "   IdentityFile ~/.ssh/id_rsa" >>"$sshconf_file"
    echo "   StrictHostKeyChecking no" >>"$sshconf_file"
    echo "   PasswordAuthentication no" >>"$sshconf_file"

    echo " " >>"$sshconf_file"
    echo "Host $haproxyserv" >>"$sshconf_file"
    echo "   User ubuntu" >>"$sshconf_file"
    echo "   HostName $floataddr_proxy1" >>"$sshconf_file"
    echo "   IdentityFile ~/.ssh/id_rsa" >>"$sshconf_file"
    echo "   StrictHostKeyChecking no" >>"$sshconf_file"
    echo "   PasswordAuthentication no" >>"$sshconf_file"
    echo "   ProxyJump $bastionserv" >>"$sshconf_file"

    echo " " >>"$sshconf_file"
    echo "Host $haproxyserv2" >>"$sshconf_file"
    echo "   User ubuntu" >>"$sshconf_file"
    echo "   HostName $floataddr_proxy2" >>"$sshconf_file"
    echo "   IdentityFile ~/.ssh/id_rsa" >>"$sshconf_file"
    echo "   StrictHostKeyChecking no" >>"$sshconf_file"
    echo "   PasswordAuthentication no" >>"$sshconf_file"
    echo "   ProxyJump $bastionserv" >>"$sshconf_file"
